# Notations
D : the total number of gene loci concerned
g : derived allele (variable)
j : a specific gene locus
n : the number of affected traits
i : a specific trait
z : trait value
o : trait values with the optimum fitness
w : fitness value

In [1]:
import numpy as np

In [18]:
def random_data_gen1(D,n,seedValue):
    rng = np.random.default_rng(seedValue)
    der_ale = rng.integers(low=0, high=3, size=D)
    phen_eff = rng.integers(low=-2,high=3,size=[D,n])

    return der_ale,phen_eff

In [19]:
D = 8; n = 10; seedValue = 102

der_ale_1 = random_data_gen1(D,n,seedValue)[0]
phen_eff_1 = random_data_gen1(D,n,seedValue)[1]
zWT_0 = np.zeros(n)
opt_phen_0 = np.zeros(n)

print(der_ale_1)
print(phen_eff_1)
print(zWT_0)
print(opt_phen_0)

[1 0 1 1 0 2 0 0]
[[-2  1  1  0 -1  2  2  0  1  2]
 [-2 -1 -2 -2  0 -1  2  1  2  0]
 [ 0  2  1  2  0  2 -2 -2  0  0]
 [ 2  1 -1  2  1 -2 -1  1  2 -2]
 [-1  1  1  0  0 -2  2 -2 -1  0]
 [-1  0 -1  0  2  2 -1  2  1 -1]
 [ 2 -2 -1 -1  0  2  0 -1  2 -2]
 [ 2  1  1  1  2 -2  2 -2  1 -2]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
a = der_ale_1 **2
print(a)
print(sum(a))

[1 0 1 1 0 4 0 0]
7


In [21]:
z_i = zWT_0 + np.matmul(der_ale_1,phen_eff_1)
print(z_i)
z_sq = (z_i - opt_phen_0)**2
print(z_sq)

[-2.  4. -1.  4.  4.  6. -3.  3.  5. -2.]
[ 4. 16.  1. 16. 16. 36.  9.  9. 25.  4.]


In [24]:
def fitness_val(der_ale,phen_eff,zWT,opt_phen):
    z_i = zWT + np.matmul(der_ale,phen_eff)
    z_sq = (z_i-opt_phen)**2
    w = np.exp(-sum(z_sq))
    log_w = np.log(w)
    return w,log_w

In [25]:
fitness_val(der_ale_1,phen_eff_1,zWT_0,opt_phen_0)

(8.628801156620959e-60, -136.0)