In [1]:
import numpy as np


In [2]:
def fitness_val(der_ale,A,zWT,O):
    z_i = zWT + np.matmul(A,der_ale)
    z_sq = np.square(z_i-O)
    w = np.ravel(np.exp(-np.sum(z_sq,axis=0))) #np.ravel to flatten matrix into a 1D array
    #log_w = np.log(w)
    return w

In [3]:
D = 5; N = 10; n = 6
rng = np.random.default_rng()
A = rng.integers(low=-2,high=3,size=[n,D])
print(A)
zWT_0 = np.zeros([n,N])
opt_phen_0 = np.zeros([n,N])
F = np.matrix(np.zeros([D,N]))
print(F)

w = fitness_val(F,A,zWT_0,opt_phen_0)
#print(np.squeeze(w,axis=0))
print(np.sum(w))
print(w.shape)
a = w/np.sum(w)
print(a)
print(a.shape)

P1_choice = np.random.choice(range(N),N,replace=True,p=a)
print(P1_choice)
print(P1_choice.dtype)

[[-2  1  0  0 -2]
 [-2 -1  0  0 -2]
 [-2  1 -2  0  0]
 [ 0  0  0 -1  2]
 [-2 -1  1 -1  0]
 [ 1 -2 -2 -1 -1]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10.0
(10,)
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
(10,)
[3 8 7 2 5 6 2 2 3 2]
int64


In [4]:
# test the numpy.random.choice function
a = np.array(range(5))
print(a)
fitness = np.array([2,100,3,5,0])

choice = np.random.choice(a,5,replace=True, p=(fitness/sum(fitness)))
print(choice)

[0 1 2 3 4]
[1 1 1 1 1]


In [5]:
# chance of choosing parent proportional to their fitness
def hybridisation_proportional_fitness(P1,P2,N,A,zWT,O,seedValue):
    rng = np.random.default_rng(seedValue)
    G = 1 #number of generations
    D = P1.shape[0]
    P1 = np.matrix(P1); P2 = np.matrix(P2)
    P1_fit = fitness_val(P1,A,zWT,O)
    P1_choice = np.random.choice(range(N),N,replace=True,p=(P1_fit)/sum(P1_fit))
    S1 = np.zeros([D,1])
    for i in P1_choice:
        s = P1[:,i]
        S1 = np.concatenate((S1,s),axis=1)
    S1 = np.delete(S1,0,1)
    P2_fit = fitness_val(P2,A,zWT,O)
    P2_choice = np.random.choice(range(N),N,replace=True,p=(P2_fit)/sum(P2_fit))
    # sample from the new population with replacement
    S2 = np.zeros([D,1])
    for i in P2_choice:
        s = P2[:,i]
        S2 = np.concatenate((S2,s),axis=1)
    S2 = np.delete(S2,0,1)

    np.place(S1,S1 == 1,rng.binomial(1,0.5,[D,N])*2)
    np.place(S2,S2 == 1,rng.binomial(1,0.5,[D,N])*2)
    F = np.matrix((S1 + S2)/2)

    while 1 in F:
        # sample two parental populations from the new population with replacement. Probability proportional to fitness
        F_fit_1 = fitness_val(F,A,zWT,O)
        P1_choice = np.random.choice(range(N),N,replace=True,p=(F_fit_1)/sum(F_fit_1))
        S1 = np.zeros([D,1])
        for i in P1_choice:
            s = F[:,i]
            S1 = np.concatenate((S1,s),axis=1)
        S1 = np.delete(S1,0,1)
        F_fit_2 = fitness_val(F,A,zWT,O)
        P2_choice = np.random.choice(range(N),N,replace=True,p=(F_fit_2)/sum(F_fit_2))
        # sample from the new population with replacement
        S2 = np.zeros([D,1])
        for i in P2_choice:
            s = F[:,i]
            S2 = np.concatenate((S2,s),axis=1)
        S2 = np.delete(S2,0,1)
        # a new hybridisation
        np.place(S1,S1 == 1,rng.binomial(1,0.5,[D,N])*2)
        np.place(S2,S2 == 1,rng.binomial(1,0.5,[D,N])*2)
        F = (S1 + S2)/2
        G += 1
        print(f"F {G}")
        print(F)
    H = np.mean(F)/2
    return F, G, H

In [6]:
D = 5; N = 10; n = 5
rng = np.random.default_rng()
P1 = np.zeros([D,N])
P2 = np.full([D,N],2)
A = rng.integers(low=-2,high=3,size=[n,D])
#print(A)
zWT_0 = np.zeros([n,N])
O = np.zeros([n,N])

print(P1)
print(np.matrix(P1))
P1 = np.matrix(P1)
for i in range(5):
    print(P1[:,i])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [7]:
D = 5; N = 10; n = 5
rng = np.random.default_rng(102)
P1 = np.zeros([D,N])
P2 = np.full([D,N],2)
A = rng.integers(low=-2,high=3,size=[n,D])
print(A)
zWT_0 = np.zeros([n,N])
O = np.zeros([n,N])

w = hybridisation_proportional_fitness(P1=P1,P2=P2,N=N,A=A,zWT=zWT_0,O=O,seedValue=None)
print(w)

[[ 0 -2  0  0 -1]
 [ 2 -1 -1 -2  1]
 [ 1  0 -1  2  2]
 [ 0  1  2 -2 -1]
 [-2 -2  0 -1  2]]
F 2
[[0. 1. 1. 2. 1. 0. 2. 2. 0. 1.]
 [0. 1. 1. 1. 2. 0. 2. 2. 1. 1.]
 [1. 1. 1. 1. 1. 2. 2. 2. 1. 0.]
 [2. 2. 1. 1. 0. 0. 2. 2. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1. 2. 2.]]
F 3
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), 3, 0.2)
