In [3]:
import numpy as np
import time

In [10]:
def hybridisation_no_selection_OptSpeed_0(P1,P2,N,seedValue):
    rng = np.random.default_rng(seedValue)
    G = 1 #number of generations
    D = P1.shape[0]
    C1 = P1 # have to keep the original draw to calculate fitness
    np.place(C1,C1 == 1,rng.binomial(1,0.5,[D,N])*2)
    C2 = P2
    np.place(C2,C2 == 1,rng.binomial(1,0.5,[D,N])*2)
    F = np.matrix((C1 + C2)/2)

    while 1 in F:
        # sample two parental populations from the new population with replacement
        b1 = rng.integers(low=0,high=N,size=N)

        S1 = np.zeros([D,1])
        for i in b1:
            s = F[:,i]
            S1 = np.concatenate((S1,s),axis=1)
        S1 = np.delete(S1,0,1)


        b2 = rng.integers(low=0,high=N,size=N)
        # sample from the new population with replacement
        S2 = np.zeros([D,1])
        for i in b2:
            s = F[:,i]
            S2 = np.concatenate((S2,s),axis=1)
        S2 = np.delete(S2,0,1)

        # a new hybridisation
        C1 = S1
        np.place(C1,C1 == 1,rng.binomial(1,0.5,[D,N])*2)

        C2 = S2
        np.place(C2,C2 == 1,rng.binomial(1,0.5,[D,N])*2)
        F = (C1 + C2)/2
        G += 1
        #print(f"F {G}")
        #print(F)
    H = np.mean(F)/2

    return F, G, H



In [11]:
D_10 = 10; N_20 = 20
A = []
H = []

tic = time.time()
for i in range(100):
    w = hybridisation_no_selection_OptSpeed_0(P1=np.zeros([10,20]),P2=np.full([10,20],2),N=20,seedValue = None)
    F = w[0]
    a = w[1]
    h = w[2]
    A.append(a)
    H.append(h)
    #print(f'F{a}\n{F}')
#print(A)
print(f"D = 10, N = 20, mean generation time: {np.mean(A)}, mean hybrid index: {np.mean(H)}")

toc = time.time()
print(f"execution took {(toc-tic):.3f} seconds")

D = 10, N = 20, mean generation time: 127.27, mean hybrid index: 0.52295
execution took 9.882 seconds


In [ ]:
gen_0_D10_N20 = [9.656,12.219,9.796,11.396,9.355]


In [16]:
# without making a copy
def hybridisation_no_selection_OptSpeed_1(P1,P2,N,seedValue):
    rng = np.random.default_rng(seedValue)
    G = 1 #number of generations
    D = P1.shape[0]
    np.place(P1,P1 == 1,rng.binomial(1,0.5,[D,N])*2)
    np.place(P2,P2 == 1,rng.binomial(1,0.5,[D,N])*2)
    F = np.matrix((P1 + P2)/2)

    while 1 in F:
        # sample two parental populations from the new population with replacement
        b1 = rng.integers(low=0,high=N,size=N)
        S1 = np.zeros([D,1])
        for i in b1:
            s = F[:,i]
            S1 = np.concatenate((S1,s),axis=1)
        S1 = np.delete(S1,0,1)
        b2 = rng.integers(low=0,high=N,size=N)
        # sample from the new population with replacement
        S2 = np.zeros([D,1])
        for i in b2:
            s = F[:,i]
            S2 = np.concatenate((S2,s),axis=1)
        S2 = np.delete(S2,0,1)
        # a new hybridisation
        np.place(S1,S1 == 1,rng.binomial(1,0.5,[D,N])*2)
        np.place(S2,S2 == 1,rng.binomial(1,0.5,[D,N])*2)
        F = (S1 + S2)/2
        G += 1
        #print(f"F {G}")
        #print(F)
    H = np.mean(F)/2
    return F, G, H

In [42]:
# sampling: replace concatenation with array.append followed by matrix rearrangement
def hybridisation_no_selection_OptSpeed_2(P1,P2,N,seedValue):
    rng = np.random.default_rng(seedValue)
    G = 1 #number of generations
    D = P1.shape[0]
    np.place(P1,P1 == 1,rng.binomial(1,0.5,[D,N])*2)
    np.place(P2,P2 == 1,rng.binomial(1,0.5,[D,N])*2)
    F = np.matrix((P1 + P2)/2)

    while 1 in F:
        # sample two parental populations from the new population with replacement
        b1 = rng.integers(low=0,high=N,size=N)
        S1 = np.array([])
        for i in b1:
            s = F[:,i]
            S1 = np.append(S1,s)
        S1 = np.reshape(np.matrix(S1),[N,D]).T
        b2 = rng.integers(low=0,high=N,size=N)
        # sample from the new population with replacement
        S2 = np.array([])
        for i in b2:
            s = F[:,i]
            S2 = np.append(S2,s)
        S2 = np.reshape(np.matrix(S2),[N,D]).T
        # a new hybridisation
        np.place(S1,S1 == 1,rng.binomial(1,0.5,[D,N])*2)
        np.place(S2,S2 == 1,rng.binomial(1,0.5,[D,N])*2)
        F = (S1 + S2)/2
        G += 1
        #print(f"F {G}")
        #print(F)
    H = np.mean(F)/2
    return F, G, H

In [45]:

w = hybridisation_no_selection_OptSpeed_2(P1=np.zeros([10,20]),P2=np.full([10,20],2),N=20,seedValue = None)
print(w[0],w[1],w[2])

In [31]:
F = np.matrix([[1,2,3,4],[5,6,7,8]])
print(F)
A = []

for i in np.array([0,3,2,1]):
    s = F[:,i]
    #print(s)
    A = np.append(A,s)
print(A)
B = np.matrix(A)
print(B)
C = np.reshape(B,[4,2]) # [N,D]
print(C)
print(C.T)


[[1 2 3 4]
 [5 6 7 8]]
[1. 5. 4. 8. 3. 7. 2. 6.]
[[1. 5. 4. 8. 3. 7. 2. 6.]]
[[1. 5.]
 [4. 8.]
 [3. 7.]
 [2. 6.]]
[[1. 4. 3. 2.]
 [5. 8. 7. 6.]]
float64


In [29]:
D_10 = 10; N_20 = 50

At = []
Ht = []
T = []

for i in range(20):
    A = []
    H = []

    tic = time.time()
    for i in range(100):
        w = hybridisation_no_selection_OptSpeed_0(P1=np.zeros([10,20]),P2=np.full([10,20],2),N=20,seedValue = None)
        #F = w[0]
        a = w[1]
        h = w[2]
        A.append(a)
        H.append(h)
        #print(f'F{a}\n{F}')
    #print(A)
    #print(f"D = 10, N = 20, mean generation time: {np.mean(A)}, mean hybrid index: {np.mean(H)}")

    toc = time.time()
    #print(f"execution took {(toc-tic):.3f} seconds")
    t = toc-tic
    T.append(t)
    At.append(np.mean(A))
    Ht.append(np.mean(H))
print(f"mean generation time \n{At}, mean of mean: {np.mean(At)}")
print(f"mean hybrid index \n{Ht}, mean of mean: {np.mean(Ht)}")
print(f"average time of 100 executions {np.mean(T):.3f} seconds")

mean generation time 
[121.37, 131.11, 127.98, 133.01, 128.36, 135.7, 135.95, 136.51, 128.03, 134.49, 135.98, 137.21, 124.4, 125.03, 132.81, 131.61, 131.58, 141.23, 120.98, 133.47], mean of mean: 131.3405
mean hybrid index 
[0.5058499999999999, 0.46904999999999997, 0.49705000000000005, 0.4991, 0.47415, 0.48499999999999993, 0.49605000000000005, 0.4978999999999999, 0.514, 0.5069, 0.5099, 0.4672, 0.49695000000000006, 0.50225, 0.47790000000000005, 0.5199999999999999, 0.4979, 0.5148999999999999, 0.47485000000000005, 0.51005], mean of mean: 0.4958475
average time of execution 9.243


In [30]:
ZD_10 = 10; N_20 = 20

At = []
Ht = []
T = []

for i in range(20):
    A = []
    H = []

    tic = time.time()
    for i in range(100):
        w = hybridisation_no_selection_OptSpeed_1(P1=np.zeros([10,20]),P2=np.full([10,20],2),N=20,seedValue = None)
        #F = w[0]
        a = w[1]
        h = w[2]
        A.append(a)
        H.append(h)
        #print(f'F{a}\n{F}')
    #print(A)
    #print(f"D = 10, N = 20, mean generation time: {np.mean(A)}, mean hybrid index: {np.mean(H)}")

    toc = time.time()
    #print(f"execution took {(toc-tic):.3f} seconds")
    t = toc-tic
    T.append(t)
    At.append(np.mean(A))
    Ht.append(np.mean(H))
print(f"mean generation time \n{At}, mean of mean: {np.mean(At)}")
print(f"mean hybrid index \n{Ht}, mean of mean: {np.mean(Ht)}")
print(f"average time of 100 executions {np.mean(T):.3f} seconds")

mean generation time 
[121.62, 135.24, 128.73, 134.13, 140.03, 135.09, 131.72, 118.92, 138.57, 127.91, 138.97, 132.48, 127.82, 136.49, 138.24, 130.64, 130.02, 131.38, 132.19, 142.09], mean of mean: 132.614
mean hybrid index 
[0.5092, 0.49705000000000005, 0.5069, 0.52765, 0.4890499999999999, 0.5199499999999999, 0.4869, 0.5232500000000001, 0.48585, 0.4999, 0.4919, 0.49475, 0.49894999999999995, 0.5121499999999999, 0.5238999999999999, 0.50985, 0.46684999999999993, 0.5130500000000001, 0.5102500000000001, 0.4790499999999999], mean of mean: 0.5023199999999999
average time of execution 8.606


In [44]:
ZD_10 = 10; N_20 = 20

At = []
Ht = []
T = []

for i in range(20):
    A = []
    H = []

    tic = time.time()
    for i in range(100):
        w = hybridisation_no_selection_OptSpeed_2(P1=np.zeros([10,20]),P2=np.full([10,20],2),N=20,seedValue = None)
        #F = w[0]
        a = w[1]
        h = w[2]
        A.append(a)
        H.append(h)
        #print(f'F{a}\n{F}')
    #print(A)
    #print(f"D = 10, N = 20, mean generation time: {np.mean(A)}, mean hybrid index: {np.mean(H)}")

    toc = time.time()
    #print(f"execution took {(toc-tic):.3f} seconds")
    t = toc-tic
    T.append(t)
    At.append(np.mean(A))
    Ht.append(np.mean(H))
print(f"mean generation time \n{At}, mean of mean: {np.mean(At)}")
print(f"mean hybrid index \n{Ht}, mean of mean: {np.mean(Ht)}")
print(f"average time of 100 executions {np.mean(T):.3f} seconds")

mean generation time 
[133.46, 128.47, 134.29, 128.69, 129.38, 130.93, 134.35, 140.81, 142.82, 131.01, 137.22, 132.19, 134.31, 135.28, 128.16, 137.28, 127.78, 129.74, 126.99, 121.76], mean of mean: 132.246
mean hybrid index 
[0.5229499999999999, 0.4838, 0.5211000000000001, 0.47690000000000005, 0.51095, 0.47785000000000005, 0.49920000000000003, 0.49584999999999996, 0.49989999999999996, 0.5300499999999999, 0.49405, 0.5049999999999999, 0.48795, 0.5208499999999999, 0.5119, 0.51315, 0.4989999999999999, 0.48690000000000005, 0.533, 0.47605], mean of mean: 0.50232
average time of 100 executions 11.775 seconds


The third attempt turns out to be the worst of all.